import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-white shadow-sm py-4 mb-8">
          <div className="mx-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Link href="/" className="flex items-center space-x-2">
                  <Image src="/logo.png" alt="Fairly Logo" className="h-8 w-8"  width={32} height={32}/>
                  <span className="text-xl font-bold text-gray-800">Fairly</span>
                </Link>
              </div>
            </div>
          </div>
        </header>
        {children}
        <footer className="mt-8 text-center text-sm text-gray-500">
          <p>Fairly - Your AI Assistant</p>
          <p className="mt-1">&copy; {new Date().getFullYear()} All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
